apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: prod
  # Other vnet resrouces need to access product-service so Internal LoadBalancer is needed  but the service still not exposed to the internet
  labels:
    app: frontend
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
    app.kubernetes.io/component: frontend
  ports:
  - name: frontend-service
    protocol: TCP
    port: 80 # the port the service is listening on externally
    targetPort: 5173 # the port the container is listening on internally