apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: prod
  # Other vnet resrouces need to access product-service so Internal LoadBalancer is needed  but the service still not exposed to the internet
  labels:
    app: product
    app.kubernetes.io/component: product
spec:
  type: ClusterIP
  selector:
    app: product
    app.kubernetes.io/component: product
  ports:
  - name: product-service
    protocol: TCP
    port: 80
    targetPort: 9000