apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: prod
  # Other vnet resrouces need to access product-service so Internal LoadBalancer is needed  but the service still not exposed to the internet
  labels:
    app: cart
    app.kubernetes.io/component: cart
spec:
  type: ClusterIP
  selector:
    app: cart
    app.kubernetes.io/component: cart
  ports:
  - name: cart-service
    protocol: TCP
    port: 80
    targetPort: 9003