apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: prod # the namespace of the service
  labels:
    app: user
    app.kubernetes.io/component: user_profile
spec:
  type: ClusterIP
  selector:
    app: user
    app.kubernetes.io/component: user_profile
  ports:
  - name: user-service
    protocol: TCP
    port: 80
    targetPort: 9001