name: CI/CD for User Service

on:
  push:
    branches: [main]
    paths: [User/**]
  pull_request:
    branches: [main]
    paths: [User/**]

defaults:
  run:
    working-directory: ./User

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      # required by CodeQL
      security-events: write
      packages: read
      # only required for workflows in private repositories, though this is a public repository
      actions: read
      contents: read
      id-token: write # Required for requesting the OIDC JWT

    steps:
      # this step copies the code from the repository to the runner
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
      - name: Install and test
        run: |
          npm ci
          npm run test

      # CodeQL Source Code Security Analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript
          build-mode: none

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Azure Login using Workload Identity (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: |
          az acr login --name ${{ vars.ACR_NAME }}

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.ACR_NAME }}/user:${{ github.sha }} ./User
          docker push ${{ vars.ACR_NAME }}/user:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: "${{ vars.ACR_NAME }}/user:${{ github.sha }}"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group ${{ vars.RESOURCE_GROUP_NAME }} --name ${{ vars.AKS_NAME }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install user ./backend-service \
            --values ./backend-service/values-user.yaml \
            --set image.repository=${{ vars.ACR_LOGIN_SERVER }}/user \
            --set image.tag=${{ github.sha }} \
            --namespace prod \
            --create-namespace
